"""
Discord Auth Service

Orchestrates the Discord identity binding flow, building on top of
:class:`~app.services.user_identity.UserIdentityManager`.

Key capabilities:
- Initiate a Discord link by generating a verification code
- Complete a Discord link by validating the code and persisting the binding
- Query the current binding status for a user
- Unlink a Discord account and clean up associated state
- List all Discord platform links for a user

Validates: Requirements 5.1, 5.2, 5.5
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from app.core.logger import get_logger
from app.services.user_identity import (
    PLATFORM_DISCORD,
    LinkResult,
    PlatformLink,
    UserIdentityManager,
)

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class DiscordLinkStatus:
    """Current Discord binding status for a system user.

    Attributes:
        is_linked: Whether the user has an active Discord binding.
        discord_user_id: The Discord user's snowflake ID, or ``None`` if not
            linked.
        discord_username: The Discord display name stored at link time, or
            ``None`` if not linked or not recorded.
        linked_at: UTC timestamp when the binding was created, or ``None``
            if not linked.
        pending_code: The active verification code waiting to be used, or
            ``None`` if no pending verification exists.
    """

    is_linked: bool
    discord_user_id: Optional[str]
    discord_username: Optional[str]
    linked_at: Optional[datetime]
    pending_code: Optional[str]


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class DiscordAuthService:
    """Service that orchestrates the Discord identity binding flow.

    All database operations are delegated to :class:`UserIdentityManager`.
    This service adds the higher-level orchestration logic: code generation,
    status aggregation, and clean unlink semantics.

    The :class:`UserIdentityManager` instance is injected at construction
    time so the service can be tested without a live database.

    Validates: Requirements 5.1, 5.2, 5.5
    """

    def __init__(self, identity_manager: UserIdentityManager) -> None:
        """Initialise the service with an identity manager.

        Args:
            identity_manager: An initialised :class:`UserIdentityManager`
                instance used for all identity operations.
        """
        self._identity_manager = identity_manager
        self.logger = get_logger(f"{__name__}.DiscordAuthService")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def initiate_discord_link(self, user_id: str) -> str:
        """Begin the Discord binding flow by generating a verification code.

        Generates a fresh 6-digit verification code via
        :meth:`UserIdentityManager.generate_verification_code`.  Any
        previously active code for the same user is replaced.

        The caller is responsible for displaying the code to the user so
        they can submit it via the Discord ``/link`` command.

        Args:
            user_id: System user identifier.

        Returns:
            A 6-digit numeric verification code string.

        Validates: Requirements 5.1, 5.5
        """
        self.logger.info(
            "Initiating Discord link",
            user_id=user_id,
        )
        code = self._identity_manager.generate_verification_code(user_id)
        self.logger.info(
            "Verification code generated for Discord link",
            user_id=user_id,
        )
        return code

    async def complete_discord_link(
        self,
        user_id: str,
        discord_user_id: str,
        code: str,
    ) -> LinkResult:
        """Complete the Discord binding flow by validating the code.

        Delegates to :meth:`UserIdentityManager.link_platform_account` which
        validates the verification code, checks for conflicts, and persists
        the binding.

        Args:
            user_id: System user identifier.
            discord_user_id: The Discord user's snowflake ID string.
            code: The 6-digit verification code previously generated by
                :meth:`initiate_discord_link`.

        Returns:
            A :class:`LinkResult` describing the outcome.  On success,
            ``result.success`` is ``True``.  On failure, ``result.error``
            contains a human-readable explanation.

        Validates: Requirements 5.1, 5.2, 5.5
        """
        self.logger.info(
            "Completing Discord link",
            user_id=user_id,
            discord_user_id=discord_user_id,
        )
        result = await self._identity_manager.link_platform_account(
            user_id=user_id,
            platform=PLATFORM_DISCORD,
            platform_user_id=discord_user_id,
            verification_token=code,
        )
        if result.success:
            self.logger.info(
                "Discord link completed successfully",
                user_id=user_id,
                discord_user_id=discord_user_id,
            )
        else:
            self.logger.warning(
                "Discord link failed",
                user_id=user_id,
                discord_user_id=discord_user_id,
                error=result.error,
            )
        return result

    async def get_link_status(self, user_id: str) -> DiscordLinkStatus:
        """Return the current Discord binding status for a user.

        Queries the active platform links and combines them with any pending
        verification code to produce a complete status snapshot.

        Args:
            user_id: System user identifier.

        Returns:
            A :class:`DiscordLinkStatus` describing the current state.

        Validates: Requirements 5.1, 5.2
        """
        self.logger.debug(
            "Fetching Discord link status",
            user_id=user_id,
        )

        links = await self._identity_manager.get_linked_platforms(user_id)
        discord_links = [lnk for lnk in links if lnk.platform == PLATFORM_DISCORD]

        # Determine pending code (if any)
        pending_code: Optional[str] = None
        entry = self._identity_manager._verification_codes.get(user_id)
        if entry is not None:
            from datetime import datetime as _dt
            from datetime import timezone

            if _dt.now(timezone.utc) <= entry.expires_at:
                pending_code = entry.code

        if discord_links:
            link = discord_links[0]
            status = DiscordLinkStatus(
                is_linked=True,
                discord_user_id=link.platform_user_id,
                discord_username=link.platform_username,
                linked_at=link.linked_at,
                pending_code=pending_code,
            )
        else:
            status = DiscordLinkStatus(
                is_linked=False,
                discord_user_id=None,
                discord_username=None,
                linked_at=None,
                pending_code=pending_code,
            )

        self.logger.debug(
            "Discord link status fetched",
            user_id=user_id,
            is_linked=status.is_linked,
        )
        return status

    async def unlink_discord(self, user_id: str) -> bool:
        """Deactivate the Discord binding for a user.

        Delegates to :meth:`UserIdentityManager.unlink_platform_account`.
        Historical data is preserved (``is_active`` is set to ``False``
        rather than deleting the row).

        Any pending verification code for the user is also cleared so that
        stale codes cannot be used after an unlink.

        Args:
            user_id: System user identifier.

        Returns:
            ``True`` if an active binding was deactivated, ``False`` if no
            active binding was found.

        Validates: Requirements 5.1, 5.2
        """
        self.logger.info(
            "Unlinking Discord account",
            user_id=user_id,
        )

        # Clear any pending verification code to prevent stale code reuse
        self._identity_manager._verification_codes.pop(user_id, None)

        result = await self._identity_manager.unlink_platform_account(
            user_id=user_id,
            platform=PLATFORM_DISCORD,
        )

        if result:
            self.logger.info(
                "Discord account unlinked successfully",
                user_id=user_id,
            )
        else:
            self.logger.warning(
                "No active Discord binding found to unlink",
                user_id=user_id,
            )
        return result

    async def get_linked_discord_accounts(self, user_id: str) -> list[PlatformLink]:
        """Return all active Discord platform links for a user.

        In the current data model a user can have at most one active Discord
        link (the ``user_platform_links`` table has a ``PRIMARY KEY (user_id,
        platform)`` constraint).  This method returns a list for forward
        compatibility with potential future multi-account support.

        Args:
            user_id: System user identifier.

        Returns:
            A list of :class:`PlatformLink` objects for the Discord platform.
            May be empty if the user has no active Discord binding.

        Validates: Requirements 5.1, 5.3
        """
        self.logger.debug(
            "Fetching linked Discord accounts",
            user_id=user_id,
        )

        all_links = await self._identity_manager.get_linked_platforms(user_id)
        discord_links = [lnk for lnk in all_links if lnk.platform == PLATFORM_DISCORD]

        self.logger.debug(
            "Linked Discord accounts fetched",
            user_id=user_id,
            count=len(discord_links),
        )
        return discord_links
